spring:
  application:
    name: BE-MOE
  main:
    banner-mode: console
  banner:
    location: static/banner.txt
  profiles:
    active: @spring.profiles.active@
payment:
  vnPay:
    url: ${VNPAY_URL}
    tmnCode: ${VNPAY_TMNCODE}
    secretKey: ${VNPAY_SECRET_KEY}
    returnUrl: http://localhost:1004/
    version: 2.1.0
    command: pay
    orderType: OTHER
logging:
  level:
    root: INFO
    web: INFO
    org.springframework: INFO
    org.apache: ERROR
    kafka: ERROR