version: '3.1'

services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql_moe_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  redis:
    image: redis:6.2-alpine
    container_name: redis_moe_container
    hostname: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  mysql-data: